### ISSUE TITLE
[1.12.2 - 0.0.1 ALPHA] Shrunken entities still pursued by Ocelots on resize

### ISSUE THREAD

**Issue by VallenFrostweaver** [the-realest-stu/Lilliputian#1]
As title states. If the entitiy that is shrunken (Shrinkage II) and pursued by Ocelots lives to resize to normal Ocelots still will pursue them.

EDIT: This could be a feature and not a bug as I always wanted an easier way of catching them. :D

**Comment by cadaverous-eris** [comment]
Eh, I'll consider it a bug. I'll probably have to teach myself a bit more about how AI works, though, since I actually used code from an older, incomplete size changing mod for ocelot AI, so I'll likely fix the other bugs first.

**Comment by cadaverous-eris** [comment]
Removed the ocelot AI in the latest update since it doesn't add much to gameplay now that players can't be resized and mob sizes are static.
