### ISSUE TITLE
[1.12.2 - 0.0.1 ALPHA] Sound effects the wrong way around.

### ISSUE THREAD

**Issue by maffe03** [the-realest-stu/Lilliputian#10]
After doing som testing I found that you take more damage the bigger you are.

Damage taken from a 6 block fall:
Shrinking II: Barely any damage
Normal: 1.5 Hearts
Growth II: 3 Hearts

The sound effects also seem to be the wrong way around.
![2017-12-24_21 13 36](https://user-images.githubusercontent.com/12485128/34328994-1d5bd6ac-e8f0-11e7-8b15-7fd1e2aeb564.png)
![2017-12-24_21 18 19](https://user-images.githubusercontent.com/12485128/34328993-1d3dadf8-e8f0-11e7-8542-e1e100c1e429.png)
![2017-12-24_21 15 27](https://user-images.githubusercontent.com/12485128/34328995-1d79450c-e8f0-11e7-883c-f5a9a0537b2d.png)
![2017-12-24_21 16 19](https://user-images.githubusercontent.com/12485128/34328996-1d966dbc-e8f0-11e7-8dd6-ec553e600208.png)

**Comment by Ordinaryperson2** [comment]
I looked into this, wondering if I could fix it myself. I found the problem code, but I'm confused, because... the increased damage seems very intentional? I wonder if I'm missing something. Or maybe it was a brain fart.

Either way, I have no idea how to compile this kind of thing so don't expect a fix from me. Just pointing out the issue.

	@SubscribeEvent
	public static void onEntityHurt(LivingHurtEvent event) {
		EntityLivingBase entity = event.getEntityLiving();
		float size = EntitySizeUtil.getEntityScale(entity);

		if (event.getSource() == DamageSource.FALL) {
			event.setAmount(event.getAmount() * Math.min(MathHelper.sqrt(size), size));
		} else {
			event.setAmount(event.getAmount() / MathHelper.sqrt(size));
		}

		if (event.getSource().getImmediateSource() != null) {
			float attackerSize = EntitySizeUtil.getEntityScale(event.getSource().getImmediateSource());

			event.setAmount(event.getAmount() * MathHelper.sqrt(size));
		}
	}

**Comment by cadaverous-eris** [comment]
Reopened, so that anyone who still experiences this bug can see that it's already been reported.

**Comment by cadaverous-eris** [comment]
Oh, wait, never mind, I take this all back, the sound effect is a bug, but fall damage scaling opposite size is very much intentional.

**Comment by cadaverous-eris** [comment]
Automatic issue closure is annoying. Anyway, reopening this __again__.

**Comment by Ordinaryperson2** [comment]
As the mod currently is, if an 8x scale player jumps they will take over half their health in fall damage. If big players are meant to take more damage then maybe there should be a small offset to fix that?

**Comment by cadaverous-eris** [comment]
The actual amount of fall damage large players take definitely needs some balancing, but that would be a different issue.

**Comment by cadaverous-eris** [comment]
Should be fixed in the latest update.
