### ISSUE TITLE
Help/Huge Suggestion (Get it? Huge?)

### ISSUE THREAD

**Issue by Salvation725** [the-realest-stu/Lilliputian#11]
I just want to say first off, I love this mod and have been trying for years to get an updated Gulliver. Thank you so much! I am very, very Interested!

1) How do we get past the cap sizes of min = .13 and Max = 8? I've tried the config

2) Could you please add picking players up and throwing them? That was so fun! 

3) Good luck with the mod and Have a Great day!

**Comment by matyklugDebbuged** [comment]
1: you can change it by command, i think this is only way that i discover.
2: i will love it. please developer(s), add it

**Comment by Salvation725** [comment]
Whats the command? I wasn’t able to find any other commands besides /setbasesize?

**Comment by matyklugDebbuged** [comment]
i mean the setbasesize... now i... ok, sorry nevermine

**Comment by TheCuddlyBear** [comment]
You cannot get passed the cap sizes

**Comment by cadaverous-eris** [comment]
The size caps were there for a reason. I have no plans to add the ability to pick up players or mobs. In fact, I recently removed the ability to change players' sizes at all.
