### ISSUE TITLE
Question about growth potions.

### ISSUE THREAD

**Issue by bryceio2** [the-realest-stu/Lilliputian#12]
A friend was doing some testing for some stuff using this mod, and encountered something that upon further testing, was discovered.

In this mod, the Growth II potions change what they hit to a 4x multiplier, where as in Gulliver, the Embiggening II potions changed what they hit to a 8x multiplier. I was wondering if this was intended, a bug, or something else?

**Comment by cadaverous-eris** [comment]
It was intended.
