### ISSUE TITLE
crash on 1.12.2

### ISSUE THREAD

**Issue by matyklug18** [the-realest-stu/Lilliputian#13]
no added mods, just launch game and try to generate superflat world. crash. in curse, it says alpha 0.0.1. 
https://pastebin.com/

**Comment by Ordinaryperson2** [comment]
This is because of a change in Forge. You can work around it by using Forge 2523 or earlier until the mod is updated (seems unlikely).
`Build 1.12.2-14.23.0.2524:
	williewillus: Move reach distance to an attribute (#4331)
	AEnterprise: Improve performance of World.collidesWithAnyBlock (#4286)`

**Comment by Boolyman** [comment]
I'm getting the same problem.  But I will just remove this from my packs if it wont work with updated forge versions.  Thats a shame.

**Comment by cadaverous-eris** [comment]
I updated the mod and removed player resizing, so this is no longer an issue.
