### ISSUE TITLE
View Height not changing on 1.12.1 version

### ISSUE THREAD

**Issue by kd8lvt** [the-realest-stu/Lilliputian#18]
Player size **visibly** changes, but viewpoint height does not. Have not tested if this affects player collision size as well.

I'm on Forge 1.12.**2**-14.23.2.2613, so that may be causing the issue. I'm using the 1.12.1 version of Lilliputian because the 1.12.2 version is crashing as stated in a different bug report.

**Comment by cadaverous-eris** [comment]
I updated the mod and removed player resizing, so this is no longer an issue.
