### ISSUE TITLE
[1.12.2 - 0.0.1 ALPHA] Growth II jump does fall damage from normal jump

### ISSUE THREAD

**Issue by VallenFrostweaver** [the-realest-stu/Lilliputian#2]
When jumping on a flat surface while under the effects of Growth II you take fall damage.

**Comment by cadaverous-eris** [comment]
That should be an easy fix, I'll take care of it next time I work on the mod.

**Comment by cadaverous-eris** [comment]
Now that players can't be resized, I have completely removed the jump height modification.
