### ISSUE TITLE
[1.12.2 - 0.0.1 ALPHA] Damage not effecting entities when another size

### ISSUE THREAD

**Issue by VallenFrostweaver** [the-realest-stu/Lilliputian#3]
When dealing or receiving damage when tiny or large or when the attacker is tiny or large no damage is done or received differently than when any are normal size.

**Comment by cadaverous-eris** [comment]
Huh, that's odd. I'll look into it.

**Comment by cadaverous-eris** [comment]
The latest update removed player resizing and should also fix this.
