### ISSUE TITLE
[Suggestion] Allow configurable size hard caps

### ISSUE THREAD

**Issue by Lykrast** [the-realest-stu/Lilliputian#4]
Having a config to either specify or simply remove the hard caps on sizes would be quite neat, even though extreme sizes would probably behave weirdly.

**Comment by cadaverous-eris** [comment]
I don't plan on removing the hard caps, becuase being much larger than 8x causes tons of lag, and collisions break below 1/8x. I can allow limits to be configured between those values, though.

**Comment by Lykrast** [comment]
Well that's a small shame then. Chiseled Me managed to go from 16x to 1/4096x size though, so maybe it *could* be possible in the far future.

**Comment by cadaverous-eris** [comment]
Yeah, it's on my to do list, but until then, the hard caps remain

**Comment by cadaverous-eris** [comment]
This mod is no longer about changing the player's size, so the size caps should be less of a concern.
