### ISSUE TITLE
Lilliputian-0.0.1-ALPHA 1.12.2 Missing Sky Bug

### ISSUE THREAD

**Issue by Lucariogirl11** [the-realest-stu/Lilliputian#6]
I have found that the mod causes a strange bug that removes the sky texture, clouds, sun, and moon from whatever worlds it's loaded up in. With shaderpacks it causes the sky to either flicker, be a solid gradient, or pure white. If I downgrade the mod version to 1.12.1 the sky returns to normal but resizing lacks to change the POV and entity size besides cosmetically.

Minecraft Version 1.12.2
The mods I am using with my setup along with Lilliputian are:
Optifine 1.12.2 HD U C6
MoVillages  1.12  ver1.5.4
ClassicCombat  1.12 ver1.0.0
MCA (Minecraft Comes Alive) 1.12 ver5.3.1universal
Radixcore 1.12 ver2.2.1universal
MorePlayerModels 1.12
Xaeros Minimap 1.12 ver1.13.9
NOTE: I have tried moving around mods to see if there were any conflicts. From doing this I found it's only when Lilliputian is in my setup that I come across this issue.

Sky before Lilliputian
![without lilliputian](https://user-images.githubusercontent.com/11690501/31840993-7c56f31c-b59c-11e7-9972-45695f56ceae.png)
Sky with Lilliputian
![with lilliputian](https://user-images.githubusercontent.com/11690501/31841014-96d4654e-b59c-11e7-948f-50d0f53ab517.png)
Lilliputian and Chocapic13 V6 Lite Shader
![with lilliputian and shader](https://user-images.githubusercontent.com/11690501/31841082-d03b0d9c-b59c-11e7-8a99-6f8f2d674c8a.png)

Thank you for your time.

**Comment by cadaverous-eris** [comment]
I updated the mod and removed player resizing, so this is no longer an issue.
