### ISSUE TITLE
Crash with this mod on Forge 14.23.0.2528

### ISSUE THREAD

**Issue by Sunconure11** [the-realest-stu/Lilliputian#7]
https://pastebin.com/wQayD7LC

**Comment by Shahelion** [comment]
Oh holy shit THIS is what's crashing. Yup, same exact thing. Something's up with player reach.

**Comment by KnightMiner** [comment]
Found the culprit for the issue I was having. In my testing I specifically narrowed this crash down to build 1.12.2-14.23.0.2524, specifically caused by MinecraftForge/MinecraftForge#4331 which changed reach distance to an attribute.

**Comment by doremyy** [comment]
So, anything below this version will not crash? I am using 14.23.1.2582 and it still crashes, with the exact same error.

**Comment by cadaverous-eris** [comment]
I updated the mod and removed player resizing, so this is no longer an issue.
